// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhcL6-XUtvTUe63s_DHwha3bPvJ-pbjU',
    appId: '1:995830119325:web:47d5d3b9df13ef69298d74',
    messagingSenderId: '995830119325',
    projectId: 'test-hti',
    authDomain: 'test-hti.firebaseapp.com',
    storageBucket: 'test-hti.appspot.com',
    measurementId: 'G-MKDQSY92CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ17z8thHAxhGxRce46tAggvV4RQCul4A',
    appId: '1:995830119325:android:e8a736d3b1c5e6c4298d74',
    messagingSenderId: '995830119325',
    projectId: 'test-hti',
    storageBucket: 'test-hti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWdE2Yuj_9nSfW3a5wfHlkcAZhbfY_oRM',
    appId: '1:995830119325:ios:716a10955582c10e298d74',
    messagingSenderId: '995830119325',
    projectId: 'test-hti',
    storageBucket: 'test-hti.appspot.com',
    iosClientId: '995830119325-0t3h8n8d8d0i0oqfcpubrtuvsi3rf58t.apps.googleusercontent.com',
    iosBundleId: 'com.example.hti',
  );
}
